# Config file for automatic testing at travis-ci.org

language: python

matrix:
  include:
    - python: "pypy3"
    - python: "pypy"
    - python: "3.7"
      dist: xenial
      sudo: true
    - python: "3.6"
    - python: "3.5"
    - python: "3.4"
    - python: "2.7"

# Use container-based infrastructure
sudo: false

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -r requirements.txt
  - pip install coverage

# command to run tests, e.g. python setup.py test
script:
  - coverage run --source pronouncing setup.py test --verbose
  - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then python -m doctest pronouncing/__init__.py; fi

after_success:
- pip install coveralls
- coveralls # send coverage to coveralls.io

after_script:
- coverage report                     # show coverage on cmd line
- pip install pycodestyle pyflakes
- pyflakes . | tee >(wc -l)           # static analysis
- pycodestyle --statistics --count .  # static analysis
